### ISSUE TITLE
Saves twice

### ISSUE THREAD

**Issue by marcustadros** [lardawge/carrierwave_backgrounder#105]
I'm using carrierwave 0.6.2 & carrierwave_backgrounder 0.1.3

Similar to issue 43, carrierwave still uploads the file (a Word doc), and carrierwave_background sends it through resque (1.23.0), so even if I scale down my workers, the file still gets uploaded, which I don't want because it ties up my app.

Was this fixed in issue 43? Help?

**Comment by seaify** [comment]
did you mean if use heroku, then this gem would not works?
