### ISSUE TITLE
Background job shouldn't be queued when remote_#{column}_url is set as empty string

### ISSUE THREAD

**Issue by kpfefferle** [lardawge/carrierwave_backgrounder#143]
I am running carrierwave_backgrounder 0.2.1 with carrierwave 0.8.0 on Rails 3.2.13. When a form containing a remote_#{column}_url submits an empty string (no value) as it does when the field exists but is left blank, a background job is being created in Delayed Job to process the versions of the image. The background job then blows up each time it tries to run because there is no image file to actually process (as CarrierWave itself ignores the empty string).

This is easily demonstrated in the console:

```
>> @object = Object.new()
>> @object.enqueue_image_background_job?
=> false
>> @object.remote_image_url = ""
>> @object.enqueue_image_background_job?
=> true  
```

**Comment by fabn** [comment]
Still getting this in rails 4.1.9 with `process_in_background :logo` and a form with text field named `remote_logo_url`. When form is submitted with blank string job `CarrierWave::Workers::ProcessAsset` is enqueued and I get a sidekiq error when processed.

**Comment by mountriv99** [comment]
Still happening, my work around is to do this:

    def remote_image_url=(url); super(url) if url.present?; end
