### ISSUE TITLE
CarrierWave::Workers::ProcessAsset failed with NameError

### ISSUE THREAD

**Issue by ghost** [lardawge/carrierwave_backgrounder#145]
Whenever I try to use the addon, I get: 
    CarrierWave::Workers::ProcessAsset failed with NameError: uninitialized constant Painting - 3 failed attempts

Using rails 3.2.13, latest version of backgrounder.

How do I resolve this?

**Comment by liyali** [comment]
@anthonycollini It would be great to hear from you if you have found a solution by any chance. Thank you! I have the same problem on staging/production with Heroku / carrierwave / delayed_job / carrierwave_backgrounder and fog.

**Comment by krnjn** [comment]
+1

**Comment by kntmrkm** [comment]
I have same problem with sucker_punch and AWS.

**Comment by nick123pig** [comment]
+1

**Comment by nick123pig** [comment]
So after playing around, I found that this has to do with the `store_dir` path. I had `#{model.id}_#{Time.now.to_i}`. I got rid of that and everything started working. Hopefully that can help someone else.

**Comment by nick123pig** [comment]
Sanity check for everyone...make you're not using `Time.now` in your `store_dir`.
