### ISSUE TITLE
Set Delayed Job priority

### ISSUE THREAD

**Issue by dignoe** [lardawge/carrierwave_backgrounder#153]
Is it possible to set the priority of the job in Delayed Job (either globally or in each uploader)?

**Comment by viniciusnz** [comment]
FYI I did this on `lib/backgrounder/support/backends.rb`
```
   ::Delayed::Job.enqueue worker.new(*args), :queue => queue_options[:queue], :priority => queue_options[:priority] || 0
```
I don't know how to write the tests for this, so anyone who does can create a pull request...

**Comment by brandonjmckay** [comment]
+1 
Is it currently possible to change the base queue with extending the worker?

**Comment by lardawge** [comment]
@brandonjmckay, The name of the queue can be set in the config. If there is something else you need, please open a ticket.

**Comment by YSavir** [comment]
Has this been implemented? I think I see it in the code, but not it's not in the documentation and the issue is still open.

Would be happy to implement/complete an implementation if necessary.

**Comment by lardawge** [comment]
Closing as 1.0 will not support DJ directly. Moving to support only ActiveJob and Sidekiq.
