### ISSUE TITLE
What's the strategy on what to display during processing?

### ISSUE THREAD

**Issue by jhilden** [lardawge/carrierwave_backgrounder#159]
I really like this gem, as it speeds up response times dramatically for users uploading images.  However, I'm a little unclear how people handle the time when the uploaded images are in processing?  What does one display on e.g. an index view that is rendered after successful upload?

It would be really nice to see some information about that in the README.

I would think the most straightforward thing to do would be to use the `image_processing` boolean on your model to determine whether to display the actual file or the uploaders `default_url` (maybe an image that says "processing").  However, I wouldn't want to do that everywhere in all my views, but only once in my Carrierwave uploader, where I also define the `default_url`.  Does anybody have an idea on how hook into the uploader like that?

Or are there other strategies that have worked well for people?  Any feedback would be appreciated.

**Comment by patricklindsay** [comment]
Might be worth adding this to the README as a recommended strategy as everyone using this gem is going to have to solve this.
