### ISSUE TITLE
Uploader specific queue

### ISSUE THREAD

**Issue by multiscan** [lardawge/carrierwave_backgrounder#162]
Hello, I have two different uploaders (one for images, one for video). Video processing takes much longer than images and will be done on a dedicated server at night time.

I would like to be able to queue the video processing jobs into their own sidekiq queue that will be consumed by the dedicated server and do not pollute the standard queue used for all other delayed tasks, including image processing.

I've tried without success to change the queue instance variable in my video uploader as suggested in [issue 48](https://github.com/lardawge/carrierwave_backgrounder/issues/48)

```
::CarrierWave::Workers::ProcessAsset.instance_variable_set('@queue', "videoproc")
::CarrierWave::Workers::StoreAsset.instance_variable_set('@queue', "videoproc")
```

Is the backgrounder a sort of singleton that is shared among all uploaders ? Any suggestion on how to obtain this (or on how to modify the code for including this feature) ?

Many thanks,

giovanni

**Comment by brandonjmckay** [comment]
@lardawge could you update the docs to show what kind of syntax that would look like?

That's what I'm trying to do, but I'm unclear on how to set a new queue name.

**Comment by brandonjmckay** [comment]
Would it be something to the effect of...

```
class MyProcessor < CarrierWave::Workers::ProcessAsset
  def queue
    :user_media_processing
  end
end
```

?
