### ISSUE TITLE
Processing multiple uploads

### ISSUE THREAD

**Issue by polivers** [lardawge/carrierwave_backgrounder#182]
I'm uploading multiple files (my model has_many :images and accepts_nested_attributes_for :images). 
The models are saved, but only the last image I upload is processed by carrierwave_backgrounder. 

I have this in my Image model: 

```
class Image < ActiveRecord::Base
    belongs_to :imageable, polymorphic: true
    mount_uploader :image, ImageUploader
    process_in_background :image
    store_in_background   :image
end
```

and in the ImageUploader: 

```
class ImageUploader < CarrierWave::Uploader::Base
    include CarrierWave::Backgrounder::Delay
    storage :fog 
    include CarrierWave::MimeTypes
    process :set_content_type
    ....
end
```

In the db, the image_tmp flag is set to true for the first upload, so Sidekiq is never given that job.  Any idea what's going wrong?

**Comment by leongg** [comment]
Hi @lardawge I think is not clear enough the difference between them. 

Thanks!
