### ISSUE TITLE
Conditional Backgrounding

### ISSUE THREAD

**Issue by summera** [lardawge/carrierwave_backgrounder#188]
I am using Carrierwave for two file uploads within a model.  The user must upload one of the two (either an image or a video) but not both.  A background job is enqueued for both files even though the user is uploading one of the two.  The job for the file which was not actually uploaded fails with the following message:

```
Errno::ENOENT: No such file or directory - ...
```

Meaning, if the user uploads an image, the video uploader will start and fail even though a video was not submitted.
How do I prevent backgrounder from backgrounding optional file fields?  I am currently using process_in_background for both files.

```
mount_uploader :image, ImageUploader
mount_uploader :video, VideoUploader

process_in_background :image
process_in_background :video
```

Thanks for the help!

**Comment by ksykulev** [comment]
This sounds like a symptom of the same issue I was having. On the carrierwave wiki it has a way for tracking dirty state: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Tracking-Dirty-State of a file.

So I overwrote the `#{column}_updated?` in my model to check the dirty state in accordance to the wiki entry. (inspired by https://github.com/lardawge/carrierwave_backgrounder/issues/206)
```
def avatar_updated?
  super && (previous_changes.has_key?(:avatar) || self.avatar.cached?.present?)
end
```
`self.avatar.cached?.present?` is used in the `before_save` hook. And then in the `after_commit` hook it uses `previous_changes.has_key?(:avatar)`.
