### ISSUE TITLE
Can't Store and Process in Background

### ISSUE THREAD

**Issue by jherdman** [lardawge/carrierwave_backgrounder#195]
My model looks like this:

```ruby
class Photo < AR::B
  mount_uploader :attachment, PhotoAttachmentUploader
  process_in_background :attachment
  store_in_background :attachment
end
```

What I'm seeing is:

1. All versions are processed immediately
2. A background job is enqueued to store the files

What I'm expecting to see is:

1. A job is enqueued to generate the versions
2. A second job is then enqueued to store them

If I flip the order of the macros for backgrounding, I see:

1. A job is enqueued to generate the versions
2. Storing the assets fails

It seems to me that the problem is that there is no `store_and_process_in_background` macro that correctly orchestrates these behaviours, and that both `store_in_background` and `process_in_background` call [the](https://github.com/lardawge/carrierwave_backgrounder/blob/67544376d711e1589ac5a2b2c084ae2423e46a4d/lib/backgrounder/orm/base.rb#L47) [same](https://github.com/lardawge/carrierwave_backgrounder/blob/67544376d711e1589ac5a2b2c084ae2423e46a4d/lib/backgrounder/orm/base.rb#L94) hook to generate their methods, thereby stomping on each other.

Am I simply missing a step? I've read through the README and the specs, and as far as I can tell I'm doing everything correctly. Is it simply that one can either upload or process in the background?

**Comment by lardawge** [comment]
After looking through all of the recent issues, could this be related to #200? Are you using master branch of carrierwave? I know this is an old issue but I am trying to get things lined out for the new year...

**Comment by jherdman** [comment]
At the time of reporting we weren't using the master branch of CarrierWave, though we are now. I'll try to budget some time this week and see if I can replicate the issue again and provide more details.

**Comment by diegorv** [comment]
Same here.

```ruby
class Contract::Image
  mount_uploader        :logo_image          , Contract::LogoImageUploader
  process_in_background :logo_image

  mount_uploader        :layout_image        , Contract::LayoutImageUploader
  process_in_background :layout_image
end
```

Pocessing isn't happening in the background. They get stuck in Sidekiq queue =/

**Comment by lardawge** [comment]
This should be fixed in master. I ran across the issue myself today. It was not in the released gem, only in master.
