### ISSUE TITLE
Error Class 	Errno::ENOENT Error Message 	No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by jianbo** [lardawge/carrierwave_backgrounder#199]
My image upload failed due to this error, I deployed using capistrano 3, I looked my tmp folder, it has a folder "1413367197-58277-9440" not "1416364250-14080-0903",

any idea?

Error Class 	Errno::ENOENT
Error Message 	No such file or directory @ rb_sysopen - /home/production/releases/20141118100410/public/uploads/tmp/1416364250-14080-0903/upload.jpg

**Comment by lardawge** [comment]
No idea. Lot's of specifics missing that I would need to know to even guess.
