### ISSUE TITLE
Broken with master branch of carrierwave (which added support for multiple uploads)

### ISSUE THREAD

**Issue by dmarkow** [lardawge/carrierwave_backgrounder#200]
[This commit](https://github.com/carrierwaveuploader/carrierwave/commit/d42bc52dc91d074c5b658daf90880daa4ed257d7) added support for "multiple uploads" via an array column, which removed the `cache_name` method on `CarrierWave::Mounter`. This breaks carrierwave_backgrounder at [lib/backgrounder/orb/base.rb:85](https://github.com/lardawge/carrierwave_backgrounder/blob/775e915b93891e4bff40651d1627e98cbfd5db44/lib/backgrounder/orm/base.rb#L85)

It looks like it was removed in favor of a `cache_names` method which returns an array. I haven't had time yet to see if it's as straightforward as referencing `cache_names.first` or something like that (though that wouldn't properly support multiple uploads).

While not an issue with the current 0.10.0 version of CarrierWave, [they will finally be releasing a new gem (0.11.0) soon](https://github.com/carrierwaveuploader/carrierwave/issues/1500) which will most likely break carrierwave_backgrounder.

**Comment by lardawge** [comment]
Thanks for reporting this. I need to get my head around that change since it is a major shift in the way carrierwave works.

**Comment by diegorv** [comment]
I think this problem is still related with issue #195

**Comment by philipgiuliani** [comment]
Can confirm that it does not work yet!
```ruby
NoMethodError (undefined method `cache_name' for #<CarrierWave::Mounter:0x007fb6963cbf28>):
  app/interactors/upload_image.rb:10:in `call'
  app/controllers/api/v1/images_controller.rb:85:in `create'
```

**Comment by talal7860** [comment]
I'm still seeing this issue.

**Comment by leongg** [comment]
Hi @lardawge  ! 
I'm using the carrierwave multi uploader and I added to my gem the carrierwave_backgrounder. The problem that I'm facing is that the generator cant be found. So, I can't install the gem and I can't change it the carrierwave version or I'll lose the multi uploader. 

What should I do? 

thanks!

**Comment by Shkrt** [comment]
facing the same issue with master branch of carrierwave-backgrounder

**Comment by IlkhamGaysin** [comment]
@lardawge would it be fixed?

**Comment by IlkhamGaysin** [comment]
@leoduquesnel thanks man, fixed it on my own :beers:

**Comment by IlkhamGaysin** [comment]
@leoduquesnel also there is a discussion on this fix https://github.com/lardawge/carrierwave_backgrounder/pull/234

**Comment by lardawge** [comment]
V1-beta has added support for multiple uploads.
