### ISSUE TITLE
Can't test with RSpec 

### ISSUE THREAD

**Issue by torstenb** [lardawge/carrierwave_backgrounder#203]
I've been trying to test my rails app together with [carrierwave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder), but so far have been unsuccessful. The test always hangs in `the thumb version` block and I have to end the terminal even. The only way I get the test to not hang is by [bypassing backgrounding](https://github.com/lardawge/carrierwave_backgrounder#bypass-backgrounding).

I am using `use_transactional_fixtures = true` in my RSpec tests.

I tried adding the [TestAfterCommit gem](https://github.com/grosser/test_after_commit) to my rails app as suggested in the [readme](https://github.com/lardawge/carrierwave_backgrounder#testing-with-rspec). That didn't work either.

I am using [carrierwave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder) together with  [Sucker Punch](https://github.com/brandonhilkert/sucker_punch).

The basic test I'm trying to get to pass is the the one shown in the [carrierwave readme](https://github.com/carrierwaveuploader/carrierwave#testing-with-carrierwave) adapted to my PropertyImage model:

```ruby
require 'rails_helper'
require 'carrierwave/test/matchers'

describe ImageUploader do
  include CarrierWave::Test::Matchers

  before(:each) do
    ImageUploader.configure do |config|
      config.storage = :file
      config.enable_processing = true
    end
    @pi = PropertyImage.new
    # Only way: turn off carrierwave_backgrounder to avoid dead-lock
    # dead-lock occurs due to use of transactional fixtures in test
    # @pi.process_image_upload = true
    @uploader = ImageUploader.new(@pi, :image)
    @uploader.store!(File.open('spec/support/images/my_test_image.jpg'))
  end

  after(:each) do
    ImageUploader.enable_processing = false
    @uploader.remove!
  end

  context 'the thumb version' do
    it "should scale down a landscape image to be exactly 200 by 200 pixels" do
      @uploader.thumb_retina.should be_no_larger_than(200, 200)
    end
  end

end
```

So is this an issue due to [carrierwave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder), [Sucker Punch](https://github.com/brandonhilkert/sucker_punch), or [RSpec](http://rspec.info/)? Or is the above just the best way to test my app and assume backgrounding will just work in production?

**Comment by lardawge** [comment]
This is most likely an issue with SuckerPunch and testing. Sidekiq has a gem to run background jobs inline... if you run it like a normal background job, it will hang because things are happening outside the current thread. I am not familiar enough with the tools for Sucker Punch to give you a good workaround on that end.
