### ISSUE TITLE
Migrate to ActiveJob

### ISSUE THREAD

**Issue by xdmx** [lardawge/carrierwave_backgrounder#204]
Now that rails 4.2 is out, it'd be useful migrating the current backend to support it, it'd simplify the current system and support all backends supported by ActiveJob (like inline and others)

**Comment by lardawge** [comment]
I am open to pull requests if you want to take a whack at it.

**Comment by piotrkaczmarek** [comment]
https://github.com/lardawge/carrierwave_backgrounder/pull/217 Please review. :)

**Comment by lardawge** [comment]
closed by #217
