### ISSUE TITLE
Unable to find tmp file on Heroku for store_in_background method

### ISSUE THREAD

**Issue by jhorsch** [lardawge/carrierwave_backgrounder#211]
I was able to get Carrierwave background working in development.  Its working great.

My next issue is getting it to work on Heroku.  I am getting the following error.

2015-03-20T23:29:03.880766+00:00 app[web.1]: ERROR: 500 || #<NoMethodError: undefined method `image_tmp=' for #<Photo:0x007ffc841e9168>>
2015-03-20T23:29:03.880780+00:00 app[web.1]: ERROR: 500 || #<NoMethodError: undefined method `image_tmp=' for #<Photo:0x007ffc841e9168>>

The image_tmp attribute exists on the Photo model as seen by my migration

Migrating to AddTempToPhotos (20150320212353)
==  AddTempToPhotos: migrating ================================================
-- add_column(:photos, :image_tmp, :string)
   -> 0.0101s
==  AddTempToPhotos: migrated (0.0102s) =======================================

Any ideas as to why I am getting this log error?

**Comment by ktaragorn** [comment]
If you see the comments in the README abt `store_in_background` it says its not meant to be used in heroku. There should be more docs about what it takes to get that to work in general case too..
