### ISSUE TITLE
Background processing + Cloudfront = Cached 403 from S3

### ISSUE THREAD

**Issue by ktaragorn** [lardawge/carrierwave_backgrounder#215]
In my application, I added your gem to speed up image upload, however after upload I display the images, which is right now a 403 since it is still being processed. 

However after processing, it is still a 403, since Cloudfront cached that 403 for a while.. 

I tried setting `default_url` in the uploader, but that doesnt seem to work if the original is uploaded but the version isnt generated. 

I understand I can get cloudfront to set a low TTL on 403s, but is there another way to solve this? I had hoped `default_url` would work..

**Comment by lardawge** [comment]
Not sure I can help with this. Setting a default url should work.
