### ISSUE TITLE
Process not updating model attributes

### ISSUE THREAD

**Issue by murtali** [lardawge/carrierwave_backgrounder#218]
I have a process in my uploader called (from carrierwave docs):

```
process :store_dimensions
  private
    def store_dimensions
      if file && model
        model.width, model.height = ::MiniMagick::Image.open(file.file)[:dimensions]
      end
    end
```
unfortunately none of the model attributes are getting saved in the delayed job process. any idea why?

when I try adding a 
```
        model.save
```
after then carrierwave throws an error.

**Comment by lardawge** [comment]
Yes, process is not being called... "process in background"

**Comment by murtali** [comment]
Why aren't the model attributes getting saved when it's processed in the background via delayed job?

**Comment by lardawge** [comment]
Solid question. Try running against master. I am about to release so if it is a bug, let's get to the bottom of it.

Also, what is the setup in your model and uploader?
