### ISSUE TITLE
Ability to turn off removing cache directory

### ISSUE THREAD

**Issue by lesniakania** [lardawge/carrierwave_backgrounder#220]
According to this document https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Delete-cache-garbage-directories if you use versions it's better to use rake task to cleanup tmp directories.

I'm running across errors like this from time to time:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/lunar/apps/sim/releases/20150810143505/public/uploads/tmp/1439184161-2760-3138/islandia001.jpg
Backtrace 
More    
store_asset.rb  16  initialize(...)
[GEM_ROOT]/gems/carrierwave_backgrounder-0.4.1/lib/backgrounder/workers/store_asset.rb:16:in `initialize'
```

I think it can be because of automatic removal.

**Comment by lardawge** [comment]
Which method are you using? This should only effect `store_in_background` since that is using a cached file. I am actually tempted to get rid of it since it only adds confusion and has limited use (I have never had a production env where I could use it).

**Comment by lesniakania** [comment]
Hm, I used it in the project where we had upload using `ng-file-upload` to our server and then using `carrierwave` to `s3`. We wanted to move sending to `s3` to background so I used your gem.
But from your response I wonder if I did it right then. Should I just use `process_in_background` instead? Would it move uploading to `s3` to background (not only processing the image)?
