### ISSUE TITLE
[Question] How to set queue on custom worker?

### ISSUE THREAD

**Issue by PikachuEXE** [lardawge/carrierwave_backgrounder#223]
I am using Sidekiq as backend
Should I just put `sidekiq_options queue: :queue_name` in my worker class?

(I am already trying :P)

**Comment by lardawge** [comment]
If you need to change the queue in a specific worker then you would need to do that. If you want to use the same queue across all apps, just set it in the config.

**Comment by PikachuEXE** [comment]
Maybe add that in README? (how to set a queue per worker)
