### ISSUE TITLE
Callback attempt made even when carrierwave enable_processing flag is false

### ISSUE THREAD

**Issue by palfvin** [lardawge/carrierwave_backgrounder#226]
fe8b3935f3ee4fcab753255e748fefb7ae2bd9ae caused this regression.

**Comment by lardawge** [comment]
Not sure what you are saying... the code you pointed to takes enable_processing into account.

**Comment by palfvin** [comment]
Sorry for being cryptic. In the right hand side of the `||`, it sends the callback method to the object before testing whether `enable_processing` is set. So if you're in a test environment, where those methods may not be set, it will blow up.

**Comment by dillonhafer** [comment]
I had the same issue and had to monkey patch `CarrierWave::Backgrounder::Delay#proceed_with_versioning?` in my test env
