### ISSUE TITLE
process_in_background not putting job in queue

### ISSUE THREAD

**Issue by amilano** [lardawge/carrierwave_backgrounder#227]
Greetings,

  I've been checking the resolved issues and it seems that in the past this one was a common issue but apparently it was resolved. Now, I'm using carrierwave backgrounder 0.4.1 and the issue persists, although this version was published long after most of the reported bugs were marked as resolved. 

Perhaps I'm not doing something properly...

My uploader:
```ruby
    # delay image processing
    include ::CarrierWave::Backgrounder::Delay
    version :thumb do
        process :resize_to_fit => [200,200]
    end
```
My model:
```ruby
    mount_uploader :src, ResourceUploader
    process_in_background :src
    # store_in_background :src
```
I'm using resque, so on the config file:
```ruby
  CarrierWave::Backgrounder.configure do |c|
    c.backend :resque, queue: :carrierwave
  end
```
carrierwave's gem is 0.10.0
carrierwave_backgrounder is 0.4.1
rmagick is 2.13.2
and resque is 1.25.2

When I set in the model to store_in_background instead of process, I'm able to see the process running in the queue, but what I really need is to upload the original image to carrierwave and after that to process it with carrierwave_backgrounder... I really don't know why process_in_background doesn't put a task in the queue.

Was this still an issue in 0.4.1? should I go up to 0.4.2?

Thanks in advance for any help...

**Comment by lardawge** [comment]
Yes, try 0.4.2.

**Comment by amilano** [comment]
Thanks for the quick response... I upgraded to 0.4.2, it still presents the same behavior. The image is uploaded to carrierwave but there's no processing afterwards. 

It still puts the src_processing field in the model to "true" or "t" in my DB, but it never leaves this state and I'm never able to see the process entering into the carrierwave queue in resque.

**Comment by amilano** [comment]
Well, I've been trying to make this work and I'm still not able to get the background version processing running... I really don't know what I'm doing wrong. 

Like I said before, the original image gets uploaded to my bucket through carrierwave, but after the saving process is done the process_in_background directive never seem to be able to place a task in rescue.

Works fine with store_in_background, but not for process_in_background.

I must be doing something wrong or there it might actually be a bug in gem(?)

**Comment by lardawge** [comment]
Are you running the correct queue? Sounds like the 'carrierwave' queue is not running...

**Comment by amilano** [comment]
I'm sure it is running cause I have a few other workers doing things after records are saved... and the store_in_background goes to resque without a problem

![screen shot 2015-10-19 at 7 39 31 pm](https://cloud.githubusercontent.com/assets/2029445/10594668/4bdb1126-7699-11e5-95d4-3d9f27f69c9d.png)
 
This is how I run resque: rake resque:work QUEUE=*

**Comment by amilano** [comment]
I even placed a "puts" into method to be called on the version to see if actually gets there and check if there was an exception not being logged or somthing... but the flag never gets printed into my logs

**Comment by lardawge** [comment]
Turn the queue off and see if a job get's added.

**Comment by amilano** [comment]
the carrierwave queue specifically? or every queue?

**Comment by amilano** [comment]
Here, waiting for the queue to be on again

![screen shot 2015-10-19 at 7 59 23 pm](https://cloud.githubusercontent.com/assets/2029445/10594913/f8939f8a-769b-11e5-8a98-819649b3f12c.png)

**Comment by lardawge** [comment]
carrierwave specifically. I want to see if a job gets added so we know if it is an issue with the worker of the model.

**Comment by amilano** [comment]
Got it... well I actually turned off resque and the jobs on the screenshot were the only ones who made it to the queues while it was down.

**Comment by amilano** [comment]
is there a way to manually put into the queue the task after the model is saved? or is it tied to the save/update process of the model?

**Comment by amilano** [comment]
I'm closing this issue... I wasn't able to make work the process_in_background option... It never got any version processing task into the respective queue although all my other workers were doing just fine.

I'm not sure if it's a bug on the gem or something related to my app configuration. I implemented my own background version processing mechanism and dropped the use of the gem.

Thanks anyway for the time and help provided.

**Comment by drselump14** [comment]
+1 same issue here ..
