### ISSUE TITLE
recreate_versions! doesn't recreate versions?

### ISSUE THREAD

**Issue by eostrom** [lardawge/carrierwave_backgrounder#23]
Using carrierwave 0.5.8 and carrierwave_backgrounder 0.0.6 and local file storage, if I call `Photo.image.recreate_versions!` it doesn't seem to regenerate the thumbnails _or_ queue up a delayed job for it. `CarrierWave::Uploader::Store#store!` is called for each active version, but it's called with no `new_file` parameter and no `@cache_id` instance variable, and so nothing ends up getting stored, and the processing callbacks are never called.

I'm looking into this, I just wanted to file an issue in case anyone else has an idea. I saw in #7 that @darrenterhune said "why are you calling `recreate_versions! in the first place?" The answer is because I've added a new thumbnail size to my uploader, and that's the method recommended in the [CarrierWave README](https://github.com/jnicklas/carrierwave). If there's a better way I'd like to know it.

**Comment by AknEp** [comment]
Why don't you write about this feature in README?
