### ISSUE TITLE
Uploader version urls return nil in rspec test environment

### ISSUE THREAD

**Issue by tmking** [lardawge/carrierwave_backgrounder#230]
I am using carrierwave_backgrounder with resque. I'm setting `Resque.inline = true` in  `spec/spec_helper.rb`, and my carrierwave initializer is setting `config.storage = :file` for the test environment. I'm using `database_cleaner` so `config.use_transactional_fixtures` is set to false.

Everything works as expected in my development environment. Photo versions are created and uploaded to S3, and I am able to access them via the `#url` method. 

However, when carrierwave_backgrounder is set to process in the background for my Photo uploader, I am experiencing spec failures because there are no urls available for the uploader versions. Calling `object.photo.url` will return a url, but `object.photo.small.url` returns nil.

**Comment by titopandub** [comment]
You need to use `UserImageUploader.enable_processing = true` on `before` block to make CarrierWave process inline and assign `process_avatar_upload = true` to the model. Also don't forget to disable processing with `UserImageUploader.enable_processing = false` on `after` block.
