### ISSUE TITLE
Store in Background with Transloadit(Remote url)

### ISSUE THREAD

**Issue by grepruby** [lardawge/carrierwave_backgrounder#236]
Hi

I am using https://transloadit.com/ to off load image uploadin/processing work out of my server. My uploader is setup to store_in_background . When I use remote url, it does actually download the image from remote url and then store the path to avatar_tmp attribute.  Which eventually takes time.

Ideally, when image is uploaded through remote url, it shouldn't download the image from remote url before putting job in background . It should take advantage of remote url in that case. 

Hope I made my point effectively for your understanding.

**Comment by lardawge** [comment]
The problem with trying to do that is there is no way to store the url you want to use in the backgrounder.

Your best bet is to build your own solution. Add a column to store the remote url and then create a background job to assign the remote url and save the record.

I have done this myself and it works great.

**Comment by grepruby** [comment]
Okay, I'll do that what you suggest. 

Can you share your code here like what you did for backgrounder and how to use that new column, if you can.
