### ISSUE TITLE
Carrierwave 1.0.0.beta and multiple uploads

### ISSUE THREAD

**Issue by davidwessman** [lardawge/carrierwave_backgrounder#246]
Hello!

Since Carrierwave is finally in 1.0.0.beta (:tada:), will work be done on supporting the new `cache_names` instead of `cache_name`?

**Comment by lardawge** [comment]
Yes, I would like to update CB to work with the newest Carrierwave. I will look into it.

**Comment by davidwessman** [comment]
Sounds great! 😄 
I do not know when it will go into a proper release.

**Comment by davidwessman** [comment]
@lardawge `Carrierwave 1.0.0` is released!

**Comment by giedriusr** [comment]
Any news on this?

**Comment by kevin-jj** [comment]
I created a pull request [#257](https://github.com/lardawge/carrierwave_backgrounder/pull/257) that upgrades to Carriverwave 1.0.0. 

would be great to be merged and then release a new version.

@lardawge @piotrkaczmarek @kntmrkm

**Comment by kovalevsky** [comment]
@lardawge @kevin-jj pr #257 just updates gemspec without fixing cache_names issue which descried above.
Any plans to add carrierwave 1.0 support?
