### ISSUE TITLE
carrierwave_backgrounder generator not found

### ISSUE THREAD

**Issue by mausconi** [lardawge/carrierwave_backgrounder#247]
Hello, I have this issue after adding the gem to my rails 5 app and running 'rails g carrierwave_backgrounder:install'

Running via Spring preloader in process 28916
Could not find generator 'carrierwave_backgrounder:install'. Maybe you meant 'responders:install', 'react:install' or 'simple_form:install'
Run `rails generate --help` for more options.

**Comment by davidwessman** [comment]
Did you run `bundle install` properly?

**Comment by mausconi** [comment]
Thank you David for your reply.
Yes I run bundle install without any issue

**Comment by sejje** [comment]
@mausconi I had the same issue. I revised my gemfile to use this repo as the source, which also required some finagling of some dependencies. Try this:

```
gem 'carrierwave', '~> 0.5'
gem 'carrierwave_backgrounder', :git => 'https://github.com/lardawge/carrierwave_backgrounder.git'
```

then `bundle update`

After I did that, I was able to run the generator.

Good luck!

**Comment by norby3** [comment]
Encountering this issue too - i'm using carrierwave 1.0 and bundle command is complaining - bundle is insisting on installing carrierwave_backgrounder-0.0.2.  is it mandatory to use carrierwave 0.5 with carrierwave_backgrounder 0.4.2 ??? 

.ps i'm also using carrierwave_aws which i think required carrierwave 1.0 

Bundler could not find compatible versions for gem "carrierwave":
  In snapshot (Gemfile.lock):
    carrierwave (= 1.0.0)

  In Gemfile:
    carrierwave (~> 1.0)

    carrierwave_backgrounder (~> 0.4.2) was resolved to 0.4.2, which depends on
      carrierwave (~> 0.5)

**Comment by srebalaji** [comment]
@sejje Thanks for the update.

**Comment by aboardoffices** [comment]
Can anyone help me out, I am getting same error

**Comment by SidOfc** [comment]
Note that when pulling from git directly, there is no guarantee that the repo will be there, could be just GH down which happens rarely, or repo owner removed (unknowingly, or w/o bad intent) the repo maybe. So I suggest when using the `git` option, fork the repo and use your own GH instead.

That said, fix worked, cheers 👍
