### ISSUE TITLE
Will carrierwave_backgrounder destroy tmp file after store_in_background?

### ISSUE THREAD

**Issue by AriosWei** [lardawge/carrierwave_backgrounder#249]
Hello there,

I am using carrierwave_backgrounder store_in_background now, because I had a lot of timeout for multiple image upload on carrierwave. CB is now running very good. However, our tmp file grows exponentially. So I have two questions here:
1. Will CB actually store uploaded file in the storage? 
2. Will CB remove tmp file after processing it? I understand that to use store_in_background means I have fully access to tmp file at the first place. But does this suggest I need to manually clean up tmp file?

Thanks

**Comment by musixite** [comment]
From what I see, it does indeed delete the tmp file.
(just change your tmp dir to a public folder and you'll see the file being created and destroyed after process)
