### ISSUE TITLE
Supports for rails 5.2

### ISSUE THREAD

**Issue by tumati123** [lardawge/carrierwave_backgrounder#280]
Could anyone confirm it's working with rails 5.2 version. I tried using carrier_backgrounder with both delayed_job, sidekiq but jobs were not created.

**Comment by HuntBurdick** [comment]
I am using it successfully on Rails 5.2 but had to add a few hacks. You can see what I did in my fork of the repo.  `https://github.com/EDealerDirect/carrierwave_backgrounder`. Checkout the git history.

**Comment by lardawge** [comment]
I have added support in master for the latest rails. Please test if you are still using this gem.

**Comment by HuntBurdick** [comment]
I assume you mean in master branch? The last release/tag I see if from 2015.

**Comment by lardawge** [comment]
Yes, I am currently adding a dummy rails app to write some tests against actual use cases. I will then feel comfortable with a release. For now, it is in master for testing,

**Comment by HuntBurdick** [comment]
Seems to work well in our development environment.
```
gem Rails "2.6.6"
gem Sidekiq "6.1.2"
```
