### ISSUE TITLE
New release based on master

### ISSUE THREAD

**Issue by p8** [lardawge/carrierwave_backgrounder#300]
Hi @lardawge,

We've been running master in production for months without any problems.
Would it be possible to release a new gem version? 🙇‍♂️ 🙏

**Comment by abdulhanan001** [comment]
I appreciate all the efforts for contributors but I am getting some issues and I create issue for that please take a look at it.

**Comment by lardawge** [comment]
I know I am late to the party. Master has been released to 0.4.3.

**Comment by abdulhanan001** [comment]
Thank you @lardawge chrees
