### ISSUE TITLE
No status change when a job fails

### ISSUE THREAD

**Issue by edwinramirez** [lardawge/carrierwave_backgrounder#81]
Hello, I'm currently using Carrierwave configured with the **process_in_background** parameter, extending RMagick to upload images and process them.

Then I added CarrierWave::Backgrounder::Delay to manage these uploads/processes as delayed jobs. Everything is working nice except for when I upload a corrupt image (for example a mp3 file with it´s extension changed to png). 

The delayed_job workers do their thing and reach the max_attempts I set in a initializer and fill in the **last_error** and **failed_at** fields in the **delayed_jobs** table. But the field **file_processing** in the table I'm mounting the uploads on stays set as **1** forever. 

Even if I set **Delayed::Worker.destroy_failed_jobs = true**, in the delayed_jobs initializer, the workers reach the max attempts to process the image file, then remove the failed job from the **delayed_jobs** table but the **file_processing** field remains set as **1**.

Do I need to override some method or set something?

**Comment by ckgagan** [comment]
I am using sidekiq as the queue for processing image. And I want to update something after the processing is completed. Documentation also never says that it has hooks for sidekiq.

How can I do it?
