### ISSUE TITLE
process vs store and upload to s3

### ISSUE THREAD

**Issue by zacksedition** [lardawge/carrierwave_backgrounder#93]
Hi.

I'm using carrierwave and fog to upload quite large files to AWS.  200-500MB files.
We do not do any processing on these files, except to upload to AWS.

I'm trying carrierwave-backgrounder to speed up this process.

Which option should I use: process_in_background or store_in_background?
Could you please explain the difference?  Could I use both?

Thanks
Zack

**Comment by BlueStrap11** [comment]
Hi

I'm using carrierwave and fog to upload video files to AWS S3 (5mb-300mb) without any processing. I am currently using "process_in_background" for carrierwave_backgrounder with sidekiq and redis. Everything works fine with files up to at least 130 MB but when I tried to upload a 260 MB video it throws a "No Memory Allocation" error. My application is deployed on Amazon EC2 instance. But when I did the same process on my system locally, it completed successfully. I am unable to understand the exact cause for it. Is the problem related to RAM availability? 

Thanks
