### ISSUE TITLE
Upload to S3 using sidekiq

### ISSUE THREAD

**Issue by krishnasrihari** [lardawge/carrierwave_backgrounder#99]
I would like to use this for background upload images to S3 using sidekiq but I found there is no sidekiq worker job running after I uploaded the image.

These are my configuration

Initailization 

``` ruby
CarrierWave::Backgrounder.configure do |c|
  # :delayed_job, :girl_friday, :sidekiq, :qu, :resque, or :qc
  c.backend :sidekiq, queue: :bg_photos 
end
```

Uploader

``` ruby
class ImageUploader < CarrierWave::Uploader::Base
    include ::CarrierWave::Backgrounder::Delay  
..
end
```

ActiveRecord Model

``` ruby
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader  
  store_in_background :image
end
```

When I run the sidekiq -q bg_photos, no workers found to upload images to S3

Did I forgot any thing to add to run under sidekiq?

**Comment by uwdevendra** [comment]
Hi above  http://rickenharp.posterous.com/using-carrierwave-caching-on-heroku  links are not working 
can you please explain trick or workaround for store_in_background so that worker and web will refer to same filesystem on heroku
